# Generated by Django 5.2.9 on 2026-01-02 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('n', models.FloatField(help_text='Nitrogen')),
                ('p', models.FloatField(help_text='Phosphorus')),
                ('k', models.FloatField(help_text='Potassium')),
                ('ec', models.FloatField(blank=True, help_text='Electrical Conductivity', null=True)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('texture', models.CharField(blank=True, max_length=50, null=True)),
                ('fe', models.FloatField(blank=True, null=True)),
                ('zn', models.FloatField(blank=True, null=True)),
                ('mn', models.FloatField(blank=True, null=True)),
                ('cu', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_score', models.FloatField(blank=True, null=True)),
                ('soil_class', models.CharField(blank=True, max_length=50, null=True)),
                ('weed_presence', models.BooleanField(default=False)),
                ('weed_details_json', models.JSONField(blank=True, null=True)),
                ('fusion_quality', models.CharField(max_length=20)),
                ('fusion_summary_text', models.TextField()),
                ('suggestions_text', models.TextField()),
                ('confidences_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imageinput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soilinput')),
            ],
        ),
    ]
