# Generated by Django 5.2.9 on 2026-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
