# Generated by Django 5.2.9 on 2026-01-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_predictionrecord_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrecord',
            name='suggestions',
        ),
    ]
